version: '3.8'

services:
  next-app:
    build: ./nextjs
    command: sh -c "npm install && npx sequelize-cli db:migrate && npm run dev"
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://next_starter:next_starter@db/next_starter
    networks:
      - internal
    depends_on:
      - db
    volumes:
      - ./nextjs:/usr/src/app/
      - node_modules-vol:/usr/src/app/node_modules
  db:
    image: postgres:14.3-alpine
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=next_starter
      - POSTGRES_DB=next_starter
      - POSTGRES_PASSWORD=next_starter
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-vol:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - '5432:5432'

networks:
  internal:

volumes:
  node_modules-vol:
  db-vol:
